const products = [
  
  {
    id: 1,
    subject: 'English',
    location: 'Block 5, Class 802',
    price: 350,
    space: 4,
    image: 'img/English.jpg',
    cartquantity: 0,
  },
  {
    id: 2,
    subject: 'Football',
    location: 'Block 6, Field 1',
    price: 425,
    space: 8,
    image: 'img/football.jpg',
    cartquantity: 0,
  },
  
  {
    id: 3,
    subject: 'Geography',
    location: 'Block 4, Geography Lab',
    price: 375,
    space: 5,
    image: 'img/Geography.jpg',
    cartquantity: 0,
  },
  {
    id: 4,
    subject: 'Physics',
    location: 'Block 8, Physics lab',
    price: 300,
    space: 7,
    image: 'img/physics.jpg',
    cartquantity: 0,
  },
  {
    id: 5,
    subject: 'Drama',
    location: 'Block 9, Acticity Room',
    price: 250,
    space: 7,
    image: 'img/drama.jpg',
    cartquantity: 0,
  },
  {
    id: 6,
    subject: 'Chinese',
    location: 'Block 10, Class-204',
    price: 300,
    space: 6,
    image: 'img/chinese.jpg',
    cartquantity: 0,
  },
  {
    id: 7,
    subject: 'Hockey',
    location: 'Block 2, Hockey Ground',
    price: 500,
    space: 9,
    image: 'img/hockey.jpg',
    cartquantity: 0,
  },
  {
    id: 8,
    subject: 'Robotics',
    location: 'Block 3, Robotics Lab',
    price: 175,
    space: 6,
    image: 'img/robot.jpg',
    cartquantity: 0,
  },
  {
    id: 9,
    subject: 'Basket Ball',
    location: 'Block 8, Basket Ball Ground',
    price: 250,
    space: 9,
    image: 'img/basketball.jpg',
    cartquantity: 0,
  },
 
  {
    id: 10,
    subject: 'Science',
    location: 'Block 11, Science Room',
    price: 250,
    space: 5,
    image: 'img/science.jpg',
    cartquantity: 0,
  },
  {
    id: 11,
    subject: 'Music',
    location: 'Block 7, Music Room',
    price: 400,
    space: 6,
    image: 'img/music.jpg',
    cartquantity: 0,
  },
  {
    id: 12,
    subject: 'Kung fu',
    location: 'Block 8, Martial Art Room',
    price: 350,
    space: 4,
    image: 'img/kungfu.jpg',
    cartquantity: 0,
  },
];